# render.yaml — Configuration file for deploying Django with PostgreSQL on Render

services:
  - type: web
    name: my-django-app
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn Project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
      - key: DEBUG
        value: false
      - key: PYTHON_VERSION
        value: 3.13
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false

databases:
  - name: mydb
    region: oregon
    plan: free
