services:
  - type: web
    name: nacos-django-app        # ✅ use a unique name (optional)
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn Project.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DATABASE_URL
        fromDatabase:
          name: nacos-db
          property: connectionString
      - key: PYTHON_VERSION
        value: 3.12.6

databases:
  - name: nacos-db
    region: oregon
    plan: free
