# Generated by Django 5.2.4 on 2025-11-01 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='achievements',
            field=models.TextField(blank=True, help_text='Past achievements and qualifications'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True, help_text='Short biography (optional)'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='campaign_poster',
            field=models.ImageField(blank=True, help_text='Campaign poster/banner', null=True, upload_to='candidates/posters/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AddField(
            model_name='candidate',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='profile_views',
            field=models.IntegerField(default=0, help_text='Number of profile views'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='slogan',
            field=models.CharField(blank=True, help_text='Campaign slogan', max_length=200),
        ),
        migrations.AddField(
            model_name='candidate',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Profile photo', null=True, upload_to='candidates/profiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
    ]
